# Libraries used for the data and for writing the paper.
library(GGally)
library(tidyverse)
library(readxl)
library(modelr)
library(dendextend)
library(mlr)
library(clValid)
library(clusterSim)
library(wbstats)
library(maps)
library(countrycode)
library(shiny)
library(viridis)
library(flextable)